# Generated by Django 4.2.7 on 2025-05-05 09:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('number_plate', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('milage', models.FloatField()),
                ('charge_hour', models.FloatField()),
                ('rental_time', models.DateTimeField()),
                ('design', models.CharField(max_length=50)),
                ('engine_size', models.CharField(max_length=20)),
                ('technology', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'bike',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('feedback_id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField()),
                ('comments', models.TextField()),
                ('user', models.ForeignKey(db_column='user_name', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'feedback',
            },
        ),
        migrations.CreateModel(
            name='Payment_Calculation',
            fields=[
                ('payment_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('base_fare', models.FloatField()),
                ('total_amount', models.FloatField()),
                ('payment_method', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'payment_calculation',
            },
        ),
        migrations.CreateModel(
            name='Station_Availability',
            fields=[
                ('station_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=100)),
                ('available_time', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'station_availability',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_no', models.CharField(max_length=15)),
                ('national_id', models.CharField(max_length=20)),
                ('membership', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ride_History',
            fields=[
                ('ride_no', models.AutoField(primary_key=True, serialize=False)),
                ('bike', models.ForeignKey(db_column='bike_number_plate', on_delete=django.db.models.deletion.CASCADE, to='authapp.bike')),
                ('end_station', models.ForeignKey(db_column='end_station_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rides_ended_here', to='authapp.station_availability')),
                ('payment_id', models.ForeignKey(db_column='payment_id', on_delete=django.db.models.deletion.CASCADE, to='authapp.payment_calculation')),
                ('start_station', models.ForeignKey(db_column='start_station_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rides_started_here', to='authapp.station_availability')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ride_history',
            },
        ),
        migrations.AddField(
            model_name='payment_calculation',
            name='ride',
            field=models.ForeignKey(db_column='ride_no', on_delete=django.db.models.deletion.CASCADE, to='authapp.ride_history'),
        ),
        migrations.CreateModel(
            name='Gives',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_id', models.ForeignKey(db_column='feedback_id', on_delete=django.db.models.deletion.CASCADE, to='authapp.feedback')),
                ('user_profile', models.ForeignKey(db_column='national_id', on_delete=django.db.models.deletion.CASCADE, to='authapp.userprofile')),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.AddField(
            model_name='bike',
            name='national_id',
            field=models.ForeignKey(db_column='national_id', on_delete=django.db.models.deletion.CASCADE, to='authapp.userprofile'),
        ),
        migrations.AddField(
            model_name='bike',
            name='station_id',
            field=models.ForeignKey(db_column='station_id', on_delete=django.db.models.deletion.CASCADE, to='authapp.station_availability'),
        ),
    ]
