# Generated by Django 4.2.11 on 2025-05-06 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment_calculation',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='payment_calculation',
            name='start_time',
        ),
        migrations.AddField(
            model_name='station_availability',
            name='position',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
