# Generated by Django 4.2.11 on 2025-05-09 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_remove_payment_calculation_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bike',
            name='charge_hour',
        ),
        migrations.RemoveField(
            model_name='bike',
            name='national_id',
        ),
        migrations.RemoveField(
            model_name='bike',
            name='rental_time',
        ),
    ]
