# Generated by Django 4.2.11 on 2025-05-10 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_remove_bike_charge_hour_remove_bike_national_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment_calculation',
            name='ride',
        ),
    ]
