# Generated by Django 4.2.21 on 2025-05-12 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_remove_payment_calculation_ride'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bike',
            name='station_id',
        ),
        migrations.AddField(
            model_name='bike',
            name='current_station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bikes', to='authapp.station_availability'),
        ),
    ]
